### ISSUE TITLE
'make tests' fails on RHEL/CentOS

### ISSUE THREAD

**Issue by tvdijen** [toddsundsted/stunt#16]
```
Error:
/opt/rh/rh-ruby23/root/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- test/unit (LoadError)
        from /opt/rh/rh-ruby23/root/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /apps/moo/dev/stunt/test/lib/test_helper.rb:1:in `<top (required)>'
        from /opt/rh/rh-ruby23/root/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /opt/rh/rh-ruby23/root/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
        from test/test_verb_cache.rb:1:in `<main>'
```

**Comment by tvdijen** [comment]
Some research showed that these gems don't come with the ruby-package on RHEL/CentOS:

# Prevent occasions where minitest is not bundled in
# packaged versions of ruby. See following issues/prs:
# https://github.com/gitlabhq/gitlabhq/issues/3826
# https://github.com/gitlabhq/gitlabhq/pull/3852
# https://github.com/discourse/discourse/pull/238

**Comment by toddsundsted** [comment]
interesting! thanks!

**Comment by toddsundsted** [comment]
fixed in https://github.com/toddsundsted/stunt/pull/17
